#!/usr/bin/env bash
# Script that start nginx as nginx user
sudo chmod 777 /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sudo pkill -9 apache
sudo service nginx restart
